apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crank-platform.fullname" . }}-config
  labels:
    {{- include "crank-platform.labels" . | nindent 4 }}
data:
  crank-environment: {{ .Values.config.crankEnvironment | quote }}
  log-level: {{ .Values.config.logLevel | quote }}
  {{- if .Values.config.database.enabled }}
  database-url: {{ .Values.config.database.url | quote }}
  {{- end }}
  {{- range $key, $value := .Values.config.custom }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}