apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crank-platform.fullname" . }}-secrets
  labels:
    {{- include "crank-platform.labels" . | nindent 4 }}
type: Opaque
data:
  platform-auth-token: {{ .Values.secrets.platformAuthToken | b64enc }}
  {{- if .Values.secrets.database.password }}
  database-password: {{ .Values.secrets.database.password | b64enc }}
  {{- end }}
  {{- range $key, $value := .Values.secrets.custom }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}